name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Run tests
      run: npm test --if-present

    - name: Create release archive
      run: |
        mkdir release
        cp -r dist package.json README.MD LICENSE CONTRIBUTING.md release/
        tar -czf openclaude-${{ github.ref_name }}.tar.gz -C release .
        zip -r openclaude-${{ github.ref_name }}.zip release/

    - name: Generate changelog
      id: changelog
      run: |
        # Get the previous tag
        PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD~1 2>/dev/null || echo "")
        
        if [ -z "$PREVIOUS_TAG" ]; then
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "Initial release of OpenClaude" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        else
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "Changes since $PREVIOUS_TAG:" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          git log --pretty=format:"- %s" $PREVIOUS_TAG..HEAD >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        fi

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: OpenClaude ${{ github.ref_name }}
        body: |
          # OpenClaude ${{ github.ref_name }}
          
          ${{ steps.changelog.outputs.changelog }}
          
          ## Installation
          
          ```bash
          # Download and extract
          wget https://github.com/RaheesAhmed/OpenClaude/releases/download/${{ github.ref_name }}/openclaude-${{ github.ref_name }}.tar.gz
          tar -xzf openclaude-${{ github.ref_name }}.tar.gz
          
          # Or clone from source
          git clone https://github.com/RaheesAhmed/OpenClaude.git
          cd OpenClaude
          npm install && npm run build
          ```
          
          ## What's New
          
          See the full changelog above for all changes in this release.
          
          ## Documentation
          
          - [README](https://github.com/RaheesAhmed/OpenClaude/blob/main/README.MD)
          - [Contributing Guide](https://github.com/RaheesAhmed/OpenClaude/blob/main/CONTRIBUTING.md)
          
          **Full Changelog**: https://github.com/RaheesAhmed/OpenClaude/compare/${{ steps.changelog.outputs.previous_tag }}...${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./openclaude-${{ github.ref_name }}.tar.gz
        asset_name: openclaude-${{ github.ref_name }}.tar.gz
        asset_content_type: application/gzip

    - name: Upload ZIP asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./openclaude-${{ github.ref_name }}.zip
        asset_name: openclaude-${{ github.ref_name }}.zip
        asset_content_type: application/zip